# -*- mode: ruby -*-

# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.

# Vagrantfile for a single Master + Agent Nodes cluster
# TODO(marco): bring it to v2 syntax
# TODO(marco): add a ZK node

Vagrant::Config.run do |config|

  config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking.
  #config.vm.box_check_update = false

  config.vm.define "master" do |master|

    # The hostname must be properly configured, or stuff won't work in the UI
    # Remember to update /etc/hosts on the dev laptop to point to the correct IP
    #   192.168.33.10    mesos.master
    master.vm.host_name = "mesos-master"

    # Forward the ports for the Master and HTTP Webserver to Host
    master.vm.forward_port 5050, 5050

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    master.vm.network "hostonly", "192.168.33.10"

    # Installs Mesos (deb pkg) and its dependencies):
    master.vm.provision "Install Mesos", type: "shell" do |s|
      s.path = "install-mesos.sh"
    end

    # Launch Mesos Master
    master.vm.provision "Run Master", type: "shell", run: "always" do |s|
        s.path = "run-master.sh"
    end
  end

  config.vm.define "agent" do |agent|

    # The hostname must be properly configured, or stuff won't work in the UI
    # Remember to update /etc/hosts on the dev laptop to point to the correct IP
    #   192.168.33.11    mesos.agent
    agent.vm.host_name = "mesos-agent"

    # Forward the ports for the Master and HTTP Webserver to Host
    agent.vm.forward_port 22, 2223
    agent.vm.forward_port 8000, 8080
    agent.vm.forward_port 5051, 5051

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    agent.vm.network "hostonly", "192.168.33.11"

    # Increase RAM for the Agent to 1GB
    config.vm.customize ["modifyvm", :id, "--memory", 1024]

    # Shares folders to the guest VM.
    agent.vm.share_folder "www", "/var/local/www", "../resources/static"

    # Enable provisioning with a shell script.
    # Installs Mesos (deb pkg) and its dependencies):
    agent.vm.provision "Install Mesos", type: "shell" do |s|
      s.path = "install-mesos.sh"
    end

    # Installing Docker on the Agent only
    agent.vm.provision "Install Docker", type: "shell" do |s|
      s.path = "install-docker.sh"
    end

    # Launch Mesos Agent
    agent.vm.provision "Run Agent Node 1", type: "shell", path: "run-agent.sh",
        run: "always"
  end

end

